### ISSUE TITLE
Error -3: invalid stored block lengths

### ISSUE THREAD

**Issue by ggavelis** [mgzip/mgzip#19]
Hi, I installed (via pip) pgzip 0.3.1, ran it in Python 3.9.4 and am getting the following error while trying to unzip a text file:

**Error:**
error: Error -3 while decompressing data: invalid stored block lengths

**My command:**

import pgzip
with pgzip.open('test.fastq.gz', "rt", thread=2) as fr:
        print(fr.read())

**Comment by alexitx** [comment]
Hi, have you tested using the built-in gzip module? This error seems to be caused by invalid or corrupt gzip file ([SO](https://stackoverflow.com/questions/10911089)). If the problem is only present in pgzip, please provide some gzipped sample data that reproduces the issue.

**Comment by timhughes** [comment]
Closing this ticket as stale. @ggavelis if there is still an issue feel free to reopen and provide some way for us to replicate the issue such as an example test.fastq.gz that is seeing the issue.

**Comment by ruochiz** [comment]
Hey, 

I'm having the same issue here. Seems that gzip library can open it but not pgzip. But if I recreate a small gzip file by: either using gunzip in CLI or gzip library in python. That small gzip file can be opened by pgzip. After some inspection, it seem that the file that cannot be openned are generated by bgzip instead of gzip. Do you think that can be the reason? Thanks. 


![CleanShot 2023-02-12 at 18 10 07](https://user-images.githubusercontent.com/8788626/218342922-53b83f38-54e2-4e4e-8a9f-9fffc6268d69.png)

**Comment by Hendricks27** [comment]
I have the same issue, it has the same behavior as mgzip.
