### ISSUE TITLE
fix tests to see if we can still support 3.6

### ISSUE THREAD

**Issue by timhughes** [mgzip/mgzip#29]
```
Run actions/setup-python@v2
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by jamestwebber** [comment]
3.6 is EOLed, doesn't seem worth supporting to me...

**Comment by alexitx** [comment]
https://github.com/actions/setup-python/issues/544
3.6 is no longer supported on ubuntu-22.04, only on ubuntu-20.04.

> 3.6 is EOLed, doesn't seem worth supporting to me...

I agree, it's EOL since 23 Dec 2021. Though in the case we still decide to support it for whatever reason, that means not testing on modern OSes or running on older versions only for the 3.6 tests (https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-adding-configurations).

**Comment by timhughes** [comment]
I am happy with that strategy.
